version: '2'

services:
  prototype:
    restart: always
    build: .
    ports:
      - "80:80"
    links:
      - db
 
  db:
    restart: always
    image: ampersandtarski/ampersand-prototype-db

  phptools:
    image: phpmyadmin/phpmyadmin
    ports:
       - "8080:80"
    links:
      - db